### ISSUE TITLE
Bug in older macOS Safari

### ISSUE THREAD

**Issue by robinoch** [rexxars/use-device-pixel-ratio#1]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `use-device-pixel-ratio@1.1.0` for the project I'm working on.

On macOS Safari 13.1.2 the error "mediaMatcher.addEventListener is not a function" appeared. The solution is to use "addListener" in this case. So I changed:
```
    mediaMatcher.addEventListener('change', updateDpr);
    return () => {
      mediaMatcher.removeEventListener('change', updateDpr);
    };
```
to the following:
```
    if (mediaMatcher.addEventListener) {
      mediaMatcher.addEventListener('change', updateDpr);
    } else {
      mediaMatcher.addListener(updateDpr);
    }
    return () => {
      if (mediaMatcher.removeEventListener) {
        mediaMatcher.removeEventListener('change', updateDpr);
      } else {
        mediaMatcher.removeListener(updateDpr);
      }
    };
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by rexxars** [comment]
Fixed in 1.1.2 - thanks for reporting!
