### ISSUE TITLE
`useEffect` is run every time if there is an `options` object.

### ISSUE THREAD

**Issue by RunDevelopment** [rexxars/use-device-pixel-ratio#2]
According to the examples in the docs, `useDevicePixelRatio` is supposed to be used with inline option objects.

Example:
```ts
const dpr = useDevicePixelRatio({maxDpr: 50})
```

However, this will cause [the internal `useEffect`](https://github.com/rexxars/use-device-pixel-ratio/blob/d155f86ac049cd635458a88cc5d1f4a19a6cfbce/index.ts#L38) to run every time `useDevicePixelRatio` is called, so [the deps array of `useEffect`](https://github.com/rexxars/use-device-pixel-ratio/blob/d155f86ac049cd635458a88cc5d1f4a19a6cfbce/index.ts#L51) is effectively useless (if an inline options object is used).

**Comment by rexxars** [comment]
Fixed in 1.1.2 - thanks for reporting!
